---
# tasks file for ubuntu_sys_config

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install additional soft
  apt:
    name: '{{ item }}'
    state: present
  with_items: '{{ soft }}'

- name: Change default text editor
  command: update-alternatives --config vim

- name: Remove Nano
  apt:
    name: "nano"
    state: absent

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Change timezone to {{ my_TZ }}
  command: timedatectl set-timezone {{ my_TZ }}

- name: Change password for root
  shell: echo "{{ item.name }}:{{ item.new_pass }}" | chpasswd
  args:
    executable: /bin/bash
  with_items: '{{ change_pass }}'


- name: Copy tmux-config to {{ ansible_ssh_user }}
  copy:
    src: tmux.conf
    dest: /home/{{ ansible_ssh_user }}/.tmux.conf
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}'

- name: Backup sshd_config
  command: mv /etc/ssh/sshd_config /etc/ssh/sshd_config.origin

- name: Copy sshd-config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify:
    - Restart sshd
