---
# Install Nginx

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Backup nginx-config and create dir fo sites
  shell: |
    mv /etc/nginx/nginx.conf /etc/nginx/nginx_conf.origin
    mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default_conf.origin
    mv /etc/nginx/sites-enabled/@default
    mkdir -p /etc/nginx/sites-{available,enabled}
    chown -R root:root /etc/nginx/sites-{available,enabled}
    chmod 751 /etc/nginx/sites-{available,enabled}
  args:
    executable: /bin/bash

- name: Copy my nginx-config file
  copy:
    src: srv_config/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '644'

- name: Change owners of nginx log-file
  command: chown -R {{ web_user }}:{{ web_user }} /var/log/nginx
  notify:
    - Restart nginx
