---
# Install php

- name: Install php7.4-fpm
  apt:
    name: '{{ item }}'
    state: present
  with_items: '{{ php74_inst }}'

- name: Backup php.ini
  command: mv /etc/php/7.4/fpm/php.ini /etc/php/7.4/fpm/php.ini.origin

- name: Copy my php.ini
  copy:
    src: srv_config/php.ini
    dest: /etc/php/7.4/fpm/php.ini
    owner: root
    group: root
    mode: '644'

- name: Create dir for info-page
  command: mkdir -p /srv/www-nginx/page_info

- name: Create info-page
  copy:
    dest: /srv/www-nginx/page_info/info.php
    content: |
      <?php
      phpinfo();
      ?>
    mode: '0644'

- name: Change owner for dir with sites
  command: chown -R {{ web_user }}:{{ web_user }} /srv

- name: Add config for info-page
  template:
    src: conf_page_info.j2
    dest: /etc/nginx/sites-available/page_info.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable start_page
  file:
    src: /etc/nginx/sites-available/page_info.conf
    dest: /etc/nginx/sites-enabled/page_info.conf
    owner: root
    group: root
    state: link
  notify:
    - Restart nginx
    - Restart php
