---
- name: create dir for info-page
  command: mkdir -p /srv/www-nginx/plug

- name: copy page fo my plug
  copy: 
    src: 'page_my_plug/{{ item }}'
    dest: '/srv/www-nginx/plug/{{ item }}'
    owner: '{{ web_user }}'
    group: '{{ web_user }}'
    mode: '0644'
  loop:
    - index.html
    - under_construction.png

- name: add config for pages with plug
  template:
    src: conf_page_plug.j2
    dest: /etc/nginx/sites-available/page_plug.conf
    owner: root
    group: root
    mode: '0644'

- name: enable start_page
  file:
    src: /etc/nginx/sites-available/page_plug.conf
    dest: /etc/nginx/sites-enabled/page_plug.conf
    owner: root
    group: root
    state: link
  notify:
    - Restart nginx