#tasks for ubuntu_web_nginx_php74fpm

- name: Include installation nginx
  include_tasks: in_nginx.yml

- name: Include installation php7.4-fpm
  include_tasks: in_php_7_4.yml

- name: Include add plug pages
  include_tasks: in_page_plug.yml

- name: Include add site for vsftpd
  include_tasks: in_vsftpd.yml

#- name: Open port for services in ufw
#  include_tasks: in_ufw.yml
